### PR TITLE
Use sanitized names in core.clj and spec.clj

### PR DESCRIPTION
**Pull request by robert-johansson**

### CODE REVIEW

**Comment by trptcolin** [comment]
This looks good to me - not sure why it wasn't using `namespace` already in those spots.

One very slight nitpick: can you capitalize the first word of the commit message? I try to follow http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html as much as possible for commit messages.

**Comment by robert-johansson** [comment]
OK, fixed!

**Comment by trptcolin** [comment]
Nice! :+1: Thanks! BTW, can you shoot me an example or 2 of project names that broke here?

**Comment by robert-johansson** [comment]
Sure, `lein new speclj foo_bar` generates namespaces `foo_bar` instead of `foo-bar`. Also, `lein new speclj foo/bar` generates file `bar/src/foo/bar/core.clj` with `(ns bar.core)` instead of file `bar/src/fooz/bar.clj` with `(ns foo.bar)`.

**Comment by robert-johansson** [comment]
Btw, I'm not sure, but it may be the case that the file `speclj-template/src/leiningen/new/speclj/project.clj` should contain `{{raw-name}}` instead of `{{name}}`.

**Pull request merged**
